export const qualified = [
        {
            id:1,
            img:"./shivam.jpg",
            name:"Shivam Pundhir"
        },
        {
            id:2,            
            name:"Mansi Purwar"
        },
        {
            id:3,
            img:"./blank.webp",
            name:"Dheeraj Upadhyay"
        },
        {
            id:3,
            img:"./blank.webp",
            name:"Shellendra"
        },
        {
            id:4,
            img:"./blank.webp",
            name:"Shellendra"
        },
        {
            id:3,
            img:"./blank.webp",
            name:"Shellendra"
        },
        {
            id:3,
            img:"./blank.webp",
            name:"Shellendra"
        },
        {
            id:3,
            img:"./blank.webp",
            name:"Shellendra"
        },
        {
            id:3,
            img:"./blank.webp",
            name:"Shellendra"
        },
        {
            id:3,
            img:"./blank.webp",
            name:"Shellendra"
        },
        {
            id:3,
            img:"./blank.webp",
            name:"Shellendra"
        },
        {
            id:3,
            img:"./blank.webp",
            name:"Shellendra"
        },
        {
            id:3,
            img:"./blank.webp",
            name:"Shellendra"
        },
        {
            id:3,
            img:"./blank.webp",
            name:"Shellendra"
        },
        {
            id:3,
            img:"./blank.webp",
            name:"Shellendra"
        },
        {
            id:3,
            img:"./blank.webp",
            name:"Shellendra"
        },
        {
            id:3,
            img:"./blank.webp",
            name:"Shellendra"
        },
        {
            id:3,
            img:"./blank.webp",
            name:"Shellendra"
        },
        {
            id:3,
            img:"./blank.webp",
            name:"Shellendra"
        },
        {
            id:3,
            img:"./blank.webp",
            name:"Shellendra"
        },
        {
            id:3,
            img:"./blank.webp",
            name:"Shellendra"
        },
        {
            id:3,
            img:"./blank.webp",
            name:"Shellendra"
        },
        {
            id:3,
            img:"./blank.webp",
            name:"Shellendra"
        },
        {
            id:3,
            img:"./blank.webp",
            name:"Shellendra"
        },
        {
            id:3,
            img:"./blank.webp",
            name:"Shellendra"
        },
        {
            id:3,
            img:"./blank.webp",
            name:"Shellendra"
        },
        {
            id:3,
            img:"./blank.webp",
            name:"Shellendra"
        },
        {
            id:3,
            img:"./blank.webp",
            name:"Shellendra"
        },
        {
            id:3,
            img:"./blank.webp",
            name:"Shellendra"
        },
        {
            id:3,
            img:"./blank.webp",
            name:"Shellendra"
        },
        {
            id:3,
            img:"./blank.webp",
            name:"Shellendra"
        },
        {
            id:3,
            img:"./blank.webp",
            name:"Shellendra"
        },
        {
            id:3,
            img:"./blank.webp",
            name:"Shellendra"
        },
        {
            id:3,
            img:"./blank.webp",
            name:"Shellendra"
        },
        {
            id:3,
            img:"./blank.webp",
            name:"Shellendra"
        },
        {
            id:3,
            img:"./blank.webp",
            name:"Shellendra"
        },
        {
            id:3,
            img:"./blank.webp",
            name:"Shellendra"
        },
        {
            id:3,
            img:"./blank.webp",
            name:"Shellendra"
        },
        {
            id:3,
            img:"./blank.webp",
            name:"Shellendra"
        },
        {
            id:3,
            img:"./blank.webp",
            name:"Shellendra"
        },
        {
            id:3,
            img:"./blank.webp",
            name:"Shellendra"
        },
        {
            id:3,
            img:"./blank.webp",
            name:"Shellendra"
        },
        {
            id:3,
            img:"./blank.webp",
            name:"Shellendra"
        },
        {
            id:3,
            img:"./blank.webp",
            name:"Shellendra"
        },
    ]